# Generated by Django 3.1.2 on 2020-10-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('lei', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('legal_address', models.CharField(blank=True, max_length=255)),
                ('legal_jurisdiction', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('maturity', models.DateField()),
                ('lei', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('legal_entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='legal_entity', to='bond.legalentity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
